from . import views
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^index.html', views.index),
    url(r'^baggage-management/addNewBag', views.addNewBag),
    url(r'^baggage-management/getSavedBags', views.getSavedBags),
    url(r'^baggage-management/getSavedBag', views.getSavedBag),
    url(r'^baggage-management/deleteBag', views.deleteBag),
    url(r'^baggage-management/editBag', views.editBag),
    url(r'^baggage-management/log-in', views.log_in),
    url(r'^baggage-management/my-baggage',views.my_baggage),
    url(r'^baggage-management/add-new-bag',views.add_new_bag),
    url(r'^baggage-management/edit-bag',views.edit_bag),
    url(r'^missing-report/report-missing-bag',views.report_missing_bag),
    url(r'^missing-report/saveReport', views.saveReport),
    url(r'^missing-report/report-submission-finished',views.report_submission_finished),
    url(r'^baggage-management/edit-bag', views.edit_bag),
    url(r'^warehouse.html', views.warehouse),
    url(r'^employee-login.html', views.employee_log_in),
    url(r'^wh-register-new-bag/baggage-appearance.html', views.baggage_appearance),
    url(r'^wh-register-new-bag/saveBagAppearance', views.saveBagAppearance),
    url(r'^wh-register-new-bag/baggage-content.html', views.baggage_content),
    url(r'^wh-register-new-bag/saveContentAndDetails', views.saveContentAndDetails),
    url(r'^wh-register-new-bag/content-one.html', views.content_one),
    url(r'^wh-register-new-bag/saveContentImageOne', views.saveContentImageOne),
    url(r'^wh-register-new-bag/content-two.html', views.content_two),
    url(r'^wh-register-new-bag/saveContentImageTwo', views.saveContentImageTwo),
    url(r'^wh-register-new-bag/registration-finished.html', views.registration_finished),
    url(r'^wh-register-new-bag/getMatchResultByBag', views.getMatchResultByBag),
    url(r'^wh-register-new-bag/saveMatchedReport', views.saveMatchedReport),
    url(r'^wh-process-report/all-reports.html', views.process_all_reports),
    url(r'^wh-process-report/matching-result-by-report.html', views.matching_result_by_report),
    url(r'^wh-process-report/closeReport', views.closeReport),
    url(r'^check-report-status/all-reports.html', views.all_reports_customer),
    url(r'^check-report-status/confirm-bag-image.html', views.confirm_bag_image),
    url(r'^check-report-status/confirm-bag-content.html', views.confirm_bag_content),
    url(r'^check-report-status/saveConfirmationId', views.saveConfirmationId),
    url(r'^check-report-status/saveContactInformation', views.saveContactInformation),
    url(r'^check-report-status/contact-information.html', views.contact_information),
    url(r'^wh-check-resolved-report/all-resolved-reports.html', views.process_resolved_report),
    url(r'^check-report-status/submitErrorMatching', views.submitErrorMatching),
    url(r'^check-report-status/error-matching.html', views.error_matching),
    url(r'.*', views.log_in),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
