# Generated by Django 2.0.3 on 2018-03-24 23:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BAGGAGE_CONTENT_IMAGE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CONTENT_IMG1', models.ImageField(upload_to='content_img')),
                ('CONTENT_IMG2', models.ImageField(upload_to='content_img')),
            ],
        ),
        migrations.CreateModel(
            name='CONTENT_DETAIL',
            fields=[
                ('ITEM_NUM', models.IntegerField(primary_key=True, serialize=False)),
                ('NAME', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CUSTOMER',
            fields=[
                ('MILEAGEPLS_NUM', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True)),
                ('FIRST_NAME', models.CharField(max_length=30)),
                ('MIDDLE_NAME', models.CharField(blank=True, max_length=30, null=True)),
                ('LAST_NAME', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CUSTOMER_BAGGAGE_DESCRIPTION',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BAG_COLOR', models.CharField(max_length=10)),
                ('BAG_SIZE', models.IntegerField()),
                ('BAG_BRAND', models.CharField(max_length=20)),
                ('ITEM1', models.BooleanField(default=False)),
                ('ITEM2', models.BooleanField(default=False)),
                ('ITEM3', models.BooleanField(default=False)),
                ('ITEM4', models.BooleanField(default=False)),
                ('ITEM5', models.BooleanField(default=False)),
                ('ITEM6', models.BooleanField(default=False)),
                ('ITEM7', models.BooleanField(default=False)),
                ('ITEM8', models.BooleanField(default=False)),
                ('ITEM9', models.BooleanField(default=False)),
                ('ITEM10', models.BooleanField(default=False)),
                ('DETAILS', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CUSTOMER_BAGGAGE_IMAGE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CUST_IMG', models.ImageField(upload_to='customer_img')),
                ('BAG_NAME', models.CharField(max_length=20)),
                ('ADD_DATE', models.DateTimeField(default=django.utils.timezone.now)),
                ('CUST_IMG_MILEAGEPLS_NUM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BAG_IMG_MILEAGE_NUM', to='Baggage_Recovery_App.CUSTOMER')),
            ],
        ),
        migrations.CreateModel(
            name='REPORT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CUST_EMAIL', models.CharField(max_length=20, null=True)),
                ('CUST_PHONE', models.IntegerField(null=True)),
                ('CUST_PERM_ADDR', models.CharField(max_length=50)),
                ('CUST_TEMP_ADDR', models.CharField(max_length=50)),
                ('TEMP_ADDR_VALID_DATE', models.CharField(max_length=50)),
                ('REPO_DATE', models.DateTimeField(default=django.utils.timezone.now)),
                ('REPO_BAG_DESC_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='REPO_BAG_DESC_ID', to='Baggage_Recovery_App.CUSTOMER_BAGGAGE_DESCRIPTION')),
                ('REPO_BAG_IMG_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='REPO_BAG_IMG_ID', to='Baggage_Recovery_App.CUSTOMER_BAGGAGE_IMAGE')),
                ('REPO_MILEAGEPLS_NUM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='REPO_MILEAGE_NUM', to='Baggage_Recovery_App.CUSTOMER')),
            ],
        ),
        migrations.CreateModel(
            name='WAREHOUSE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WAREHOUSE_REPO_STAT', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WAREHOUSE_BAGGAGE_DESCRIPTION',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BAG_COLOR', models.CharField(max_length=10)),
                ('BAG_SIZE', models.IntegerField()),
                ('BAG_BRAND', models.CharField(max_length=20)),
                ('ITEM1', models.BooleanField(default=False)),
                ('ITEM2', models.BooleanField(default=False)),
                ('ITEM3', models.BooleanField(default=False)),
                ('ITEM4', models.BooleanField(default=False)),
                ('ITEM5', models.BooleanField(default=False)),
                ('ITEM6', models.BooleanField(default=False)),
                ('ITEM7', models.BooleanField(default=False)),
                ('ITEM8', models.BooleanField(default=False)),
                ('ITEM9', models.BooleanField(default=False)),
                ('ITEM10', models.BooleanField(default=False)),
                ('DETAILS', models.CharField(max_length=1000, null=True)),
                ('BAG_DESC_WAREHOUSE_BAG_ID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='BAG_DESC_WAREHOUSE_BAG_ID', to='Baggage_Recovery_App.WAREHOUSE')),
            ],
        ),
        migrations.CreateModel(
            name='WAREHOUSE_BAGGAGE_IMAGE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WAREHOUSE_IMG', models.ImageField(upload_to='warehouse_img')),
                ('WAREHOUSE_IMG_BAG_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='WAREHOUSE_IMG_BAG_ID', to='Baggage_Recovery_App.WAREHOUSE')),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='REPO_WAREHOUSE_BAG_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='REPO_WAREHOUSE_BAG_ID', to='Baggage_Recovery_App.WAREHOUSE'),
        ),
        migrations.AddField(
            model_name='baggage_content_image',
            name='CONTENT_WAREHOUSE_BAG_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CONTENT_WAREHOUSE_BAG_ID', to='Baggage_Recovery_App.WAREHOUSE'),
        ),
    ]
