# Generated by Django 2.0.3 on 2018-04-03 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Baggage_Recovery_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='REPORT_POTENTIAL_BAG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NUM', models.IntegerField(null=True)),
                ('BAG_ID1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='BAG_ID1', to='Baggage_Recovery_App.WAREHOUSE')),
                ('BAG_ID2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='BAG_ID2', to='Baggage_Recovery_App.WAREHOUSE')),
                ('BAG_ID3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='BAG_ID3', to='Baggage_Recovery_App.WAREHOUSE')),
            ],
        ),
    ]
