# Generated by Django 2.0.3 on 2018-04-06 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Baggage_Recovery_App', '0005_report_repo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='CONFIRMATION_DATE',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
