# Generated by Django 2.0.3 on 2018-04-06 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Baggage_Recovery_App', '0006_report_confirmation_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baggage_content_image',
            old_name='CONTENT_IMG1',
            new_name='CONTENT_IMG',
        ),
        migrations.RemoveField(
            model_name='baggage_content_image',
            name='CONTENT_IMG2',
        ),
    ]
