# Generated by Django 2.0.3 on 2018-04-06 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Baggage_Recovery_App', '0007_auto_20180406_0332'),
    ]

    operations = [
        migrations.CreateModel(
            name='CONFIRMATION_DETAIL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CUST_EMAIL', models.CharField(max_length=20, null=True)),
                ('CUST_PHONE', models.IntegerField(null=True)),
                ('CONFIRMATION_DATE', models.CharField(max_length=50, null=True)),
                ('CONFRIM_BAG_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CONFRIM_BAG_ID', to='Baggage_Recovery_App.WAREHOUSE')),
                ('CONFRIM_CONTENT_ID1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CONFRIM_CONTENT_ID1', to='Baggage_Recovery_App.BAGGAGE_CONTENT_IMAGE')),
                ('CONFRIM_CONTENT_ID2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CONFRIM_CONTENT_ID2', to='Baggage_Recovery_App.BAGGAGE_CONTENT_IMAGE')),
            ],
        ),
        migrations.RemoveField(
            model_name='report',
            name='CONFIRMATION_DATE',
        ),
        migrations.RemoveField(
            model_name='report',
            name='CUST_EMAIL',
        ),
        migrations.RemoveField(
            model_name='report',
            name='CUST_PHONE',
        ),
        migrations.AddField(
            model_name='confirmation_detail',
            name='REPO_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='REPO_ID', to='Baggage_Recovery_App.REPORT'),
        ),
    ]
