# Generated by Django 2.0.3 on 2018-04-10 17:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Baggage_Recovery_App', '0008_auto_20180406_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmation_detail',
            name='CUST_PHONE',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customer_baggage_image',
            name='ADD_DATE',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 10, 17, 39, 31, 601629, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='report',
            name='REPO_DATE',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 10, 17, 39, 31, 604304, tzinfo=utc)),
        ),
    ]
