# Generated by Django 2.0.3 on 2018-04-11 19:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Baggage_Recovery_App', '0009_auto_20180410_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_baggage_description',
            name='BAG_SIZE',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='customer_baggage_image',
            name='ADD_DATE',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='report',
            name='REPO_DATE',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
